// Auto-generated by dex-creator. Do not edit.

import * as tarnadasNearIntentsDepositModule from "@tarnadas/near-intents-deposit";
import "@tarnadas/near-intents-deposit/dist/styles.css";
export const dexPlugins = [
  { pluginId: "tarnadas-near-intents-deposit", module: tarnadasNearIntentsDepositModule },
] as const;
